version: "3.7"
services:
  app:
    build:
      args:
        user: mricloud96
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: user-central-service
    container_name: user-central-service-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - user-central-service

  nginx:
    image: nginx:alpine
    container_name: user-central-service-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - user-central-service

networks:
  user-central-service:
    driver: bridge
